mod auxiliary_viewer;
mod error;
mod focus;
mod mode;
mod mode_adapter;
mod mode_runtime;
mod operator_identity;
mod popup_shell;
mod preset;
mod remote_remap;
mod repair;
mod resolver;
mod runtime;
mod slot_registry;
mod swap;
mod teardown;
mod tmux;
mod topology;

pub use auxiliary_viewer::AuxiliaryViewerAction;
pub use auxiliary_viewer::AuxiliaryViewerOutcome;
pub use auxiliary_viewer::auxiliary_viewer;
pub use error::SessionError;
pub use focus::FocusSlotOutcome;
pub use focus::focus_slot;
pub use mode::SlotMode;
pub use mode_adapter::ModeLaunchContract;
pub use mode_adapter::TeardownHook;
pub use mode_adapter::mode_launch_contract;
pub use mode_runtime::RemoteModeContext;
pub use mode_runtime::SharedServerAttachConfig;
pub use mode_runtime::SlotModeSwitchOutcome;
pub use mode_runtime::switch_slot_mode;
pub use operator_identity::resolve_operator_identity_for_remote_prefix;
pub use popup_shell::PopupShellAction;
pub use popup_shell::PopupShellOutcome;
pub use popup_shell::toggle_popup_shell;
pub use preset::LayoutPreset;
pub use preset::LayoutPresetOutcome;
pub use preset::apply_layout_preset;
pub use remote_remap::OPENCODE_REMOTE_DIR_PREFIX_ENV;
pub use remote_remap::RemotePathResolution;
pub use remote_remap::resolve_remote_path;
pub use repair::SessionDamageAnalysis;
pub use repair::SessionRepairExecution;
pub use repair::SessionRepairOutcome;
pub use repair::analyze_session_damage;
pub use repair::reconcile_session_damage;
pub use repair::repair_current_project_session;
pub use repair::repair_project_session;
pub use resolver::SessionIdentity;
pub use resolver::resolve_session_identity;
pub use runtime::SessionAction;
pub use runtime::SessionLaunchOutcome;
pub use runtime::ensure_current_project_session;
pub use runtime::ensure_project_session;
pub use runtime::ensure_project_session_with_remote_prefix;
pub use slot_registry::CANONICAL_SLOT_IDS;
pub use slot_registry::SlotBinding;
pub use slot_registry::SlotRegistry;
pub use slot_registry::SlotRegistryError;
pub use slot_registry::assign_worktrees_to_slots;
pub use slot_registry::build_registry_for_canonical_panes;
pub use swap::PaneWidthSample;
pub use swap::ZoomFlagSupport;
pub use swap::pick_center_pane;
pub use swap::tmux_diagnostics_exit_status;
pub use swap::zoom_flag_support_for_command;
pub use teardown::TeardownOutcome;
pub use teardown::teardown_session;
pub use tmux::{ProcessTmuxClient, TmuxClient};
pub use topology::CENTER_WIDTH_TOLERANCE_PCT;
pub use topology::DEFAULT_CENTER_WIDTH_PCT;
pub use topology::THREE_PANE_CENTER_TARGET_PCT;
pub use topology::THREE_PANE_SIDE_TARGET_PCT;
pub use topology::THREE_PANE_TARGET_TOLERANCE_PCT;
pub use topology::canonical_five_pane_column_widths;
pub use topology::three_pane_target_widths;
pub use topology::three_pane_widths_within_tolerance;
